=== Svendell/Computer_Markup_Languages/Lab11_XML_Valid XML Documents/3.xsd
<xs:schema
xmlns:xs="http://www.w3.org/2001/XMLSchema">
 <xs:element name="body">
 <xs:complexType>
 <xs:sequence>
	 <xs:element name="people" maxOccurs="unbounded">
		 <xs:complexType>
			 <xs:sequence>
				 <xs:element name="name" type="xs:string"/>
				 <xs:element name="surname" type="xs:string"/>
				 <xs:element name="type" type="xs:string"/>
				 <xs:element name="awards" type="xs:string"/>
			 </xs:sequence>
		 </xs:complexType>
	 </xs:element>
 </xs:sequence>
 </xs:complexType>
 </xs:element>
</xs:schema>

=== Svendell/Computer_Markup_Languages/Lab11_XML_Valid XML Documents/3.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="1.css"?>
<body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="3.xsd">
    <people>
        <name>Дарья</name>
        <surname>Домрачева</surname>
        <type>Биатлон</type>
        <awards>Олимпийское золото 2014</awards>
    </people>
    <people>
        <name>Алла</name>
        <surname>Цупер</surname>
        <type>Фристайл</type>
        <awards>Олимпийское золото 2014</awards>
    </people>
    <people>
        <name>Антон</name>
        <surname>Кушнир</surname>
        <type>Фристайл</type>
        <awards>Олимпийское золото 2014</awards>
    </people>
</body>
